can:
  devices:
  - instance: CAN1
    name: CAN1
  - instance: CAN2
    name: CAN2
  enabled: true
dwt:
  enabled: true
gpio:
  configs:
  - custom_name: USER_KEY
    has_exti: true
    ioc_label: USER_KEY
    pin: PA0-WKUP
  - custom_name: ACCL_CS
    has_exti: false
    ioc_label: ACCL_CS
    pin: PA4
  - custom_name: GYRO_CS
    has_exti: false
    ioc_label: GYRO_CS
    pin: PB0
  - custom_name: SPI2_CS
    has_exti: false
    ioc_label: SPI2_CS
    pin: PB12
  - custom_name: HW0
    has_exti: false
    ioc_label: HW0
    pin: PC0
  - custom_name: HW1
    has_exti: false
    ioc_label: HW1
    pin: PC1
  - custom_name: HH
    has_exti: false
    ioc_label: hh
    pin: PC2
  - custom_name: ACCL_INT
    has_exti: true
    ioc_label: ACCL_INT
    pin: PC4
  - custom_name: GYRO_INT
    has_exti: true
    ioc_label: GYRO_INT
    pin: PC5
  - custom_name: CMPS_INT
    has_exti: true
    ioc_label: CMPS_INT
    pin: PG3
  - custom_name: CMPS_RST
    has_exti: false
    ioc_label: CMPS_RST
    pin: PG6
  enabled: true
i2c:
  devices:
  - instance: I2C1
    name: OLED
  enabled: true
mm:
  enabled: true
pwm:
  configs:
  - channel: TIM_CHANNEL_1
    custom_name: TIM8_CH1
    label: TIM8_CH1
    timer: TIM8
  - channel: TIM_CHANNEL_3
    custom_name: LASER
    label: LASER
    timer: TIM3
  - channel: TIM_CHANNEL_3
    custom_name: BUZZER
    label: BUZZER
    timer: TIM4
  - channel: TIM_CHANNEL_2
    custom_name: TIM1_CH2
    label: TIM1_CH2
    timer: TIM1
  - channel: TIM_CHANNEL_3
    custom_name: TIM1_CH3
    label: TIM1_CH3
    timer: TIM1
  - channel: TIM_CHANNEL_4
    custom_name: TIM1_CH4
    label: TIM1_CH4
    timer: TIM1
  - channel: TIM_CHANNEL_1
    custom_name: TIM1_CH1
    label: TIM1_CH1
    timer: TIM1
  - channel: TIM_CHANNEL_1
    custom_name: IMU_HEAT_PWM
    label: IMU_HEAT_PWM
    timer: TIM10
  - channel: TIM_CHANNEL_1
    custom_name: LED_B
    label: LED_B
    timer: TIM5
  - channel: TIM_CHANNEL_2
    custom_name: LED_G
    label: LED_G
    timer: TIM5
  - channel: TIM_CHANNEL_3
    custom_name: LED_R
    label: LED_R
    timer: TIM5
  - channel: TIM_CHANNEL_2
    custom_name: TIM8_CH2
    label: TIM8_CH2
    timer: TIM8
  enabled: true
spi:
  devices:
  - instance: SPI1
    name: BMI088
  enabled: true
time:
  enabled: true
uart:
  devices:
  - instance: USART3
    name: DR16
  - instance: UART5
    name: AI
  enabled: true
