from __future__ import annotations

import hashlib
import json
import os
import tempfile
from pathlib import Path
from typing import Any

from .config import MCodeConfig
from .errors import ConfigurationError, GenerationConflict
from .models import ChangeAction, FileChange, GenerationPlan, PackageManifest, ProjectModel


STATE_PATH = Path(".mrobot/generated-state.json")


def _hash(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def _safe_target(root: Path, relative: str) -> Path:
    path = (root / relative).resolve()
    try:
        path.relative_to(root.resolve())
    except ValueError as exc:
        raise ConfigurationError(f"生成目标不能位于项目目录之外: {relative}") from exc
    return path


def _state(root: Path) -> dict[str, Any]:
    path = root / STATE_PATH
    if not path.exists():
        return {"schema_version": 1, "files": {}}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ConfigurationError(f"生成状态文件损坏 {path}: {exc}") from exc
    if not isinstance(data.get("files"), dict):
        raise ConfigurationError(f"生成状态文件缺少 files: {path}")
    return data


def _render_cmake(files: list[str], cmake_path: str) -> str:
    sources = sorted(path for path in files if Path(path).suffix.lower() in {".c", ".cc", ".cpp", ".cxx", ".s"})
    includes = sorted({Path(path).parent.as_posix() for path in files if Path(path).suffix.lower() in {".h", ".hh", ".hpp"}})
    lines = ["# Generated by MCode. Do not edit; include this file from CMakeLists.txt.", ""]
    lines.append("set(MCODE_SOURCES")
    base = Path(cmake_path).parent
    source_paths = [os.path.relpath(path, base).replace(os.sep, "/") for path in sources]
    include_paths = [os.path.relpath(path, base).replace(os.sep, "/") for path in includes]
    lines.extend(f'    "${{CMAKE_CURRENT_LIST_DIR}}/{path}"' for path in source_paths)
    lines.extend([")", "", "set(MCODE_INCLUDE_DIRS"])
    lines.extend(f'    "${{CMAKE_CURRENT_LIST_DIR}}/{path}"' for path in include_paths)
    lines.extend([
        ")",
        "",
        "if(MCODE_SOURCES)",
        "    target_sources(${CMAKE_PROJECT_NAME} PRIVATE ${MCODE_SOURCES})",
        "endif()",
        "if(MCODE_INCLUDE_DIRS)",
        "    target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE ${MCODE_INCLUDE_DIRS})",
        "endif()",
        "",
    ])
    return "\n".join(lines)


def _desired_files(config: MCodeConfig, project: ProjectModel, packages: tuple[PackageManifest, ...]) -> dict[str, tuple[bytes, str, str | None]]:
    desired: dict[str, tuple[bytes, str, str | None]] = {}
    package_destinations: list[str] = []
    for package in packages:
        root = Path(package.root)
        for item in package.files:
            destination = Path(item.destination).as_posix()
            if destination.startswith("/") or destination == ".." or destination.startswith("../"):
                raise ConfigurationError(f"非法包目标路径: {destination}")
            if destination in desired:
                raise ConfigurationError(f"多个包生成同一目标: {destination}")
            desired[destination] = ((root / item.source).read_bytes(), item.policy, package.package_id)
            package_destinations.append(destination)

    generated_root = Path(config.generated_root).as_posix().rstrip("/")
    metadata_path = f"{generated_root}/mcode-project.generated.json"
    metadata = {
        "schema_version": 1,
        "generator": "MCode",
        "project": project.to_dict(),
        "packages": [package.to_dict() for package in packages],
    }
    desired[metadata_path] = ((json.dumps(metadata, ensure_ascii=False, indent=2) + "\n").encode(), "generated", None)
    cmake_path = f"{generated_root}/MCode.generated.cmake"
    desired[cmake_path] = (_render_cmake(package_destinations, cmake_path).encode(), "generated", None)
    ioc_bytes = Path(project.ioc_path).read_bytes()
    lock_packages = []
    for package in packages:
        digest = hashlib.sha256()
        for item in sorted(package.files, key=lambda value: value.source):
            digest.update(item.source.encode())
            digest.update((Path(package.root) / item.source).read_bytes())
        lock_packages.append({
            "id": package.package_id,
            "version": package.version,
            "type": package.package_type,
            "content_sha256": digest.hexdigest(),
        })
    lock = {
        "schema_version": 1,
        "generator": "MCode",
        "project": {
            "platform": "stm32cubemx",
            "mcu": project.mcu,
            "ioc": Path(project.ioc_path).name,
            "ioc_sha256": _hash(ioc_bytes),
        },
        "packages": lock_packages,
    }
    desired["mrobot.lock"] = ((json.dumps(lock, ensure_ascii=False, indent=2) + "\n").encode(), "generated", None)
    return desired


def build_plan(config: MCodeConfig, project: ProjectModel, packages: tuple[PackageManifest, ...]) -> GenerationPlan:
    root = config.root.resolve()
    state = _state(root)
    old_files: dict[str, Any] = state["files"]
    desired = _desired_files(config, project, packages)
    changes: list[FileChange] = []

    for relative, (content, policy, package_id) in sorted(desired.items()):
        target = _safe_target(root, relative)
        next_hash = _hash(content)
        previous = old_files.get(relative) if isinstance(old_files.get(relative), dict) else None
        previous_hash = previous.get("sha256") if previous else None
        if not target.exists():
            action, reason = ChangeAction.CREATE, "目标文件不存在"
        elif policy == "scaffold":
            action, reason = ChangeAction.SKIP, "scaffold 文件已存在，归用户所有"
        else:
            current_hash = _hash(target.read_bytes())
            if current_hash == next_hash:
                action, reason = ChangeAction.NOOP, "内容未变化"
            elif previous_hash is None:
                action, reason = ChangeAction.CONFLICT, "现有文件不在 MCode 所有权记录中"
            elif current_hash != previous_hash:
                action, reason = ChangeAction.CONFLICT, "文件在上次生成后被手工修改"
            else:
                action, reason = ChangeAction.UPDATE, "生成输入发生变化"
        changes.append(FileChange(relative, action, policy, reason, content, previous_hash, next_hash, package_id))

    for relative, previous in sorted(old_files.items()):
        if relative in desired or not isinstance(previous, dict):
            continue
        target = _safe_target(root, relative)
        previous_hash = previous.get("sha256")
        if not target.exists():
            action, reason = ChangeAction.NOOP, "已移除的生成文件不存在"
        elif _hash(target.read_bytes()) == previous_hash:
            action, reason = ChangeAction.DELETE, "包已移除，清理 MCode 所有的旧文件"
        else:
            action, reason = ChangeAction.CONFLICT, "旧生成文件已被手工修改，拒绝删除"
        changes.append(FileChange(relative, action, "generated", reason, None, previous_hash, None, previous.get("package_id")))
    return GenerationPlan(str(root), tuple(changes), packages)


def _atomic_write(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(handle, "wb") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def apply_plan(plan: GenerationPlan) -> None:
    if plan.has_errors:
        conflicts = [change.path for change in plan.changes if change.action == ChangeAction.CONFLICT]
        raise GenerationConflict("存在生成冲突，未写入任何文件: " + ", ".join(conflicts))
    root = Path(plan.project_root)
    backups: dict[Path, bytes | None] = {}
    actionable = [change for change in plan.changes if change.action in {ChangeAction.CREATE, ChangeAction.UPDATE, ChangeAction.DELETE}]
    try:
        for change in actionable:
            target = _safe_target(root, change.path)
            backups[target] = target.read_bytes() if target.exists() else None
            if change.action == ChangeAction.DELETE:
                target.unlink(missing_ok=True)
            else:
                content = change.content.encode() if isinstance(change.content, str) else change.content
                if content is None:
                    raise ConfigurationError(f"生成计划缺少内容: {change.path}")
                _atomic_write(target, content)
        files = {
            change.path: {
                "sha256": change.next_hash,
                "policy": change.policy,
                "package_id": change.package_id,
            }
            for change in plan.changes
            if change.next_hash and change.policy == "generated" and change.action != ChangeAction.CONFLICT
        }
        _atomic_write(root / STATE_PATH, (json.dumps({"schema_version": 1, "files": files}, ensure_ascii=False, indent=2) + "\n").encode())
    except Exception:
        for path, content in reversed(tuple(backups.items())):
            if content is None:
                path.unlink(missing_ok=True)
            else:
                _atomic_write(path, content)
        raise
